### ISSUE TITLE
Four of your packages provide the feature `init`

### ISSUE THREAD

**Issue by tarsius** [proofit404/ac-anaconda#4]
Four of your packages, `c-anaconda`, `anaconda-mode`, `company-anaconda`, `company-tern`, contain an elisp file named `init.el` that provide the feature `init`. That's not good for a few reasons:

- There shouldn't be multiple libraries (elisp files that provide a feature) with the same name.
- You cannot do `(require 'init)` and know which of these files will be loaded (unless you make sure one and only one is on the `load-path`). So you have to provide the path anyway when loading one of these files.
- The names of libraries and the features they should provide should have a package-specific prefix.

I recommend you do one of the following (decreasing preference):

- Rename to `<package>-init.el` and remove the provide form.
- Rename to `<package>-init.el` and adjust the feature accordingly.
- Remove the provide form only.
- Add the file `script/.nosearch` (see `normal-top-level-add-subdirs-to-load-path`).

**Comment by proofit404** [comment]
This files are developer scripts and were excluded from the melpa build. Is it still a problem?

**Comment by tarsius** [comment]
Thanks for removing the `(provide 'test-helper)`s!

Here the situation is similar; the issue is mostly cosmetic but there is a small risk of `load-path` pollution. This doesn't affect Melpa users, but people who run your packages directly from the git repositories are affected. There are various reasons why someone might do that.

Some, like me, simply use git submodules to install packages. I am not really affected by this issue though, because my package manager [`borg`](https://github.com/emacscollective/borg) avoids this by only adding the top-level to the `load-path` (or `lisp/` if that exists). (I wish I could just add every directory that contains elisp files to the `load-path` instead, but that is not an option because many packages have issues like this one. Unfortunately that means that for some packages I have to manually add an additional directory. E.g. for Org I have to add `contrib/lisp/` in addition to `lisp/`.)

But there is another group of users who are much more likely to just use `normal-top-level-add-to-load-path` to be sure everything that is needed is on the `load-path`: users who temporarily use the git repositories in order to contribute to you packages. Those are the users you really want to be able to run the tests. ;-)

**Comment by tarsius** [comment]
So what do you think?

**Comment by proofit404** [comment]
Done.

Sorry I was overloaded (as usual) with other projects and completely forgot about this issue.

**Comment by tarsius** [comment]
No problem, that's why I pinged ;-)
Thanks!
